mcf: Fix to enable fetching of open commit hash (v6.2.9)
:Release Notes:
Modify the mcf script to allow fetching revisions from open commit
hash to streamline the integrated build process by using the open
commit status

:Detailed Notes:
Check the open hash of the remote repository with the
"git ls-remote" command and obtain the "refs/changes/*" value
This is used to fetch the new revision by the
wait_for_git_mirror function.

This is the important command added in changes
git ls-remote origin | grep <hash> | awk '{print $2}

- Before modification
~/build$ ./mcf raspberrypi4-64
Traceback (most recent call last):
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'git checkout -B master
df30892622' returned non-zero exit status 128.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
~~~
Exception: Failed to fetch meta-webos repo

- After modification
~/build$ ./mcf raspberrypi4-64
2024-11-21T14:29:53 INFO __main__ Updating [meta-webos]
2024-11-21T14:29:53 INFO __main__ MCF: trying to fetch revision
df30892622 in p/meta-webos attempt 1 from 30
remote: Counting objects: 16, done
remote: Finding sources: 100% (11/11)
remote: Total 11 (delta 7), reused 9 (delta 7)
Unpacking objects: 100% (11/11), 6.81 KiB | 536.00 KiB/s, done.
From meta-webos
 * branch                  refs/changes/38/450038/49 -> FETCH_HEAD
2024-11-21T14:30:01 INFO __main__ Done updating [meta-webos]

:Testing Performed:
Locally tested

:QA Notes:
N/A

:Issues Addressed:
[WRR-11264] CCC: Apply fetching function for open commit hash to mcf
[WRR-11157] Improve mcf to enable fetching of open commit hash